### ISSUE TITLE
TypeError: parentPluginConfig.plugins is not iterable

### ISSUE THREAD

**Issue by Bartozzz** [saitho/semantic-release-backmerge#3]
`release.config.js`:

```js
module.exports = {
  plugins: [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    "@semantic-release/npm",
    "@semantic-release/git",
    "@semantic-release/github",
    ["@saithodev/semantic-release-backmerge", { branchName: "development" }],
  ],
};
```

**Job:**

https://github.com/Bartozzz/queue-promise/runs/824625873

**Logs:**

```
[12:23:40 AM] [semantic-release] [@saithodev/semantic-release-backmerge] › ℹ  Release succeeded. Performing back-merge into branch "development".
[12:23:41 AM] [semantic-release] › ✖  Failed step "success" of plugin "@saithodev/semantic-release-backmerge"
[12:23:41 AM] [semantic-release] [@saithodev/semantic-release-backmerge] › ℹ  Loading plugins
[12:23:41 AM] [semantic-release] › ✖  An error occurred while running semantic-release: TypeError: parentPluginConfig.plugins is not iterable
    at Object.loadPlugins (/home/runner/work/queue-promise/queue-promise/node_modules/@saithodev/semantic-release-backmerge/dist/helpers/plugins.js:38:45)
    at /home/runner/work/queue-promise/queue-promise/node_modules/@saithodev/semantic-release-backmerge/dist/perform-backmerge.js:54:35
    at Generator.next (<anonymous>)
    at /home/runner/work/queue-promise/queue-promise/node_modules/@saithodev/semantic-release-backmerge/dist/perform-backmerge.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/work/queue-promise/queue-promise/node_modules/@saithodev/semantic-release-backmerge/dist/perform-backmerge.js:4:12)
    at triggerPluginHooks (/home/runner/work/queue-promise/queue-promise/node_modules/@saithodev/semantic-release-backmerge/dist/perform-backmerge.js:52:12)
    at Object.<anonymous> (/home/runner/work/queue-promise/queue-promise/node_modules/@saithodev/semantic-release-backmerge/dist/perform-backmerge.js:36:15)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/queue-promise/queue-promise/node_modules/@saithodev/semantic-release-backmerge/dist/perform-backmerge.js:5:58) {
  pluginName: '@saithodev/semantic-release-backmerge'
}
AggregateError: 
    TypeError: parentPluginConfig.plugins is not iterable
        at Object.loadPlugins (/home/runner/work/queue-promise/queue-promise/node_modules/@saithodev/semantic-release-backmerge/dist/helpers/plugins.js:38:45)
        at /home/runner/work/queue-promise/queue-promise/node_modules/@saithodev/semantic-release-backmerge/dist/perform-backmerge.js:54:35
        at Generator.next (<anonymous>)
        at /home/runner/work/queue-promise/queue-promise/node_modules/@saithodev/semantic-release-backmerge/dist/perform-backmerge.js:8:71
```

**Comment by saitho** [comment]
Default value `[]` for `plugins` doesn't seem to work. Will have a look at it.

**Comment by saitho** [comment]
Please try **v1.1.2**, should be working there. :)
