### ISSUE TITLE
bug: fails with latest semantic-release version

### ISSUE THREAD

**Issue by EinfachHans** [saitho/semantic-release-backmerge#38]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Just received this error:

```
[8:42:47 AM] [semantic-release] [@saithodev/semantic-release-backmerge] › ✘  Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/runner/work/xxx/node_modules/semantic-release/lib/get-git-auth-url.js from /Users/runner/work/xxx/node_modules/@saithodev/semantic-release-backmerge/dist/perform-backmerge.js not supported. 
[282](https://github.com/xxx/actions/runs/3890965311/jobs/6640863500#step:7:283)
Instead change the require of get-git-auth-url.js in /Users/runner/work/xxx/node_modules/@saithodev/semantic-release-backmerge/dist/perform-backmerge.js to a dynamic import() which is available in all CommonJS modules.
[283](https://github.com/xxx/actions/runs/3890965311/jobs/6640863500#step:7:284)
    at /Users/runner/work/xxx/node_modules/@saithodev/semantic-release-backmerge/dist/perform-backmerge.js:73:31
[284](https://github.com/xxx/actions/runs/3890965311/jobs/6640863500#step:7:285)
    at Generator.next (<anonymous>)
[285](https://github.com/xxx/actions/runs/3890965311/jobs/6640863500#step:7:286)
    at fulfilled (/Users/runner/work/xxx/node_modules/@saithodev/semantic-release-backmerge/dist/perform-backmerge.js:5:58)
[286](https://github.com/xxx/actions/runs/3890965311/jobs/6640863500#step:7:287)
Error: Process completed with exit code 1.
```

Probably relevant to breaking change in 20.0.0 that semantic release is now ESM-only

### Expected Behavior

It should work with 20.0.0

### Steps To Reproduce

Use this plugin with the latest semantic-release version

### Environment

```markdown
- **semantic-release/semantic-release** version: 20.0.2
- **@saithodev/semantic-release-backmerge** version: 2.1.2
```

**Comment by saitho** [comment]
Thanks for the report. I'll take a look at it.
For now I published a bugfix release that prevents installing this plugin with semantic-release v20.
